# Generated by Django 3.2.9 on 2021-11-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='title',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='profilePicture',
            field=models.ImageField(upload_to='uploaded/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projectImage',
            field=models.ImageField(upload_to='uploaded/'),
        ),
    ]
