# Generated by Django 3.2.9 on 2021-11-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaber', '0002_auto_20211106_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='liveLink',
            field=models.URLField(default='www.google.com'),
            preserve_default=False,
        ),
    ]
