# Generated by Django 3.2.9 on 2021-11-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaber', '0003_projects_livelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
