# Generated by Django 3.2.9 on 2021-11-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaber', '0004_social_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='resume',
            field=models.FileField(default='ss', upload_to='uploaded/'),
            preserve_default=False,
        ),
    ]
