# Generated by Django 3.2.9 on 2021-11-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaber', '0005_about_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='gitLink',
            field=models.URLField(blank=True),
        ),
    ]
