# Generated by Django 3.2.9 on 2021-11-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaber', '0006_alter_projects_gitlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='aboutDescription',
            field=models.TextField(),
        ),
    ]
