# Generated by Django 3.2.9 on 2021-11-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaber', '0007_alter_about_aboutdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='tools',
            field=models.CharField(max_length=256),
        ),
    ]
