# Generated by Django 3.2.9 on 2021-11-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaber', '0009_alter_projects_livelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
