# Generated by Django 3.2.9 on 2021-11-24 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jaber', '0010_projects_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='projects',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
